//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppointmentDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int appointmentId { get; set; }
        public System.DateTime appointmentStartDate { get; set; }
        public System.DateTime appointmentEndDate { get; set; }
        public string memo { get; set; }
        public bool cancelled { get; set; }
        public bool confirmed { get; set; }
        public bool completed { get; set; }
    }
}
